### ISSUE TITLE
Many of the subtitle for the series is down

### ISSUE THREAD

**Issue by luckiluck** [lowlevel-1989/msubtitles-report#11] opened 2024-11-16 07:54 UTC
When I select to open any of a episode from any series, the subtitle cannot be load and the web site cannot be found is return.

Some of the new uploaded subtitles still can be loaded but the old one are almost down.

Could you please give it a look?
Thank you.

**Comment by lowlevel-1989** [comment] 2024-11-23 21:56
> When I select to open any of a episode from any series, the subtitle cannot be load and the web site cannot be found is return.
> 
> Some of the new uploaded subtitles still can be loaded but the old one are almost down.
> 
> Could you please give it a look? Thank you.

Thank you very much for your help, the problem is now fixed in v1.5.1.4.

**Closed as completed by lowlevel-1989** 2024-11-23 21:56 UTC
