### ISSUE TITLE
Error when try to add a subtitle from GH

### ISSUE THREAD

**Issue by alipasijaner** [lowlevel-1989/msubtitles-report#12] opened 2024-11-23 19:02 UTC
Currently, I cannot add any subtitles. When I try to add a subtitle from GitHub, I get the error:
"Url: We exclusively support the SRT format, but for loading multiple items in the background, we also offer support for YAML."

Even though it is an SRT subtitle, I still encounter the same error. I even tried adding subtitles that I had previously added successfully, but I get the same error.

**Comment by lowlevel-1989** [comment] 2024-11-23 21:56
> [alipasijaner](/alipasijaner)

Thank you very much for your help, the problem is now fixed in v1.5.1.4, I have changed your profile to public so I can put you in the credits, as well as increase your subtitle limits.

**Closed as completed** 2024-11-23 21:56 UTC

**Comment by alipasijaner** [comment] 2024-11-23 22:19
Thank you!

**Comment by alipasijaner** [comment] 2024-11-23 22:26
Okay, I uploaded the subtitle for Silo, and this time it went through without any issues.
